spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:file:/app/data/portdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
logging:
  level:
    org.springframework: info
  file:
    path: /app/log
server:
  servlet:
    encoding:
      force-response: true

url:
  upbit: https://api.upbit.com
  ubci: https://crix-api-cdn.upbit.com